# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "pnpm" 
    directories: 
      - "packages/*" 
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[npm] "
  - package-ecosystem: "github-actions" 
    directory: "/" # dependsabot magically works this out for actions
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[gha] "
